services:
  backend:
    build:
      context: ./backend
    container_name: aksflora-backend
    restart: always
    ports:
      - "5001:5000"
    environment:
      DB_HOST: aksdb1.core2cuyudba.us-east-1.rds.amazonaws.com  # Replace with your actual RDS endpoint
      DB_USER: admin
      DB_PASSWORD: AkritiAkshra29
      DB_NAME: aksdb1
    command: sh -c "sleep 20 && npm run dev"

  frontend:
    build:
      context: ./frontend
    container_name: aksflora-frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend
